---
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cliffano/command-docker-action@v1.0.0
        with:
          command: 'make ci update-to-latest update-to-main'
          image: cliffano/studio
          shell: bash
      - uses: cliffano/command-docker-action@v1.0.0
        with:
          command: 'make update-to-version TARGET_PIEMAKER_VERSION=1.0.0'
          image: cliffano/studio
          shell: bash
